### ISSUE TITLE
Concurrent sitemap generation

### ISSUE THREAD

**Issue by slavone** [ikeikeikeike/some-sitemap#14]
Hey, i am writing an app that should generate sitemaps for multiple websites. 

Currently it doesnt work correctly concurrently because of the shared states, stored in Agents. Looking through Sitemap.State code, i found that there are functions for starting named agents. But all of the agents start as single instances.

Am i missing something, is there a way to store an isolated state for every :generate call? Or is this kind of behaviour not supported?

Thanks for your time in advance!

**Comment by ikeikeikeike** [comment]
There's still nothing way to concurrency in shared data...
But supposedly, I have idea that to be changed concurrent shared data that is nested supervisor tree which typically used from Elixir library like Ecto or something else.

Therefore, I label enhancement this issue then I will try to implement that to generate multiple sitemap sometime soon. 

Thanks!
